In [1]:
import numpy as np 

In [6]:
arr = np.array([12,2,421,12,23])
arr

array([ 12,   2, 421,  12,  23])

In [7]:
l = [12,2,3412,32]
l

[12, 2, 3412, 32]

In [9]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
arr = np.arange(1,11,3)
arr 

array([ 1,  4,  7, 10])

In [22]:
arr = np.array((2,34,5,4))
arr 

array([ 2, 34,  5,  4])

In [32]:
arr = np.random.randint(5,10,20)
print(arr)
np.reshape(arr, (4,5))


[9 9 9 6 6 8 9 9 6 9 8 7 5 6 9 7 7 9 6 8]


array([[9, 9, 9, 6, 6],
       [8, 9, 9, 6, 9],
       [8, 7, 5, 6, 9],
       [7, 7, 9, 6, 8]])

In [36]:
arr.size

20

In [38]:
arr.shape

(20,)

In [1]:
import numpy as np

sudoku = np.array([
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
])

sudoku

ModuleNotFoundError: No module named 'numpy'