In [1]:
import numpy as np



🔰 EASY QUESTIONS
Create a 3x3 identity matrix.

Generate a 1D array of even numbers between 10 and 30.

Find the max, min, and mean of the array:

python
Copy
Edit
arr = np.array([1, 8, 5, 6, 3])
Get the shape and size of:

python
Copy
Edit
np.array([[1, 2], [3, 4], [5, 6]])


In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [14]:
arr = np.array([1, 8, 5, 6, 3])
np.max(arr)
np.min(arr)

1

In [15]:
df = np.array([[1, 2], [3, 4], [5, 6]])
np.shape(df)


(3, 2)

⚙️ MEDIUM QUESTIONS
Create a 5x5 matrix with values from 1 to 25.

Extract the 2nd column from a 2D array.

Replace all values > 50 with 0 in this array:

python
Copy
Edit
np.random.randint(10, 100, (5, 5))
Create an array, reshape it from 1D to 3x4.

In [23]:
mat = np.reshape(np.arange(1,26),(5,5))
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
mat[:,1]

array([ 2,  7, 12, 17, 22])

In [27]:
 mat2 = np.random.randint(10, 100, (5, 5))
mat2

array([[11, 97, 62, 93, 35],
       [31, 74, 63, 66, 95],
       [85, 37, 41, 35, 12],
       [60, 14, 85, 86, 97],
       [29, 51, 99, 78, 87]])

In [33]:
mat2[mat2 > 50] = 0
mat2

array([[11,  0,  0,  0, 35],
       [31,  0,  0,  0,  0],
       [ 0, 37, 41, 35, 12],
       [ 0, 14,  0,  0,  0],
       [29,  0,  0,  0,  0]])

In [37]:
mat = np.arange(1,13)
np.reshape(mat,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

🔥 HARD QUESTIONS (You focus here)
1. Find the row with the max sum
python
Copy
Edit
arr = np.random.randint(1, 100, (4, 5))
max_row_index = np.argmax(np.sum(arr, axis=1))
2. Sort 2D array by the second column
python
Copy
Edit
arr = np.array([
    [1, 4, 2],
    [3, 1, 5],
    [7, 0, 6]
])
arr_sorted = arr[arr[:, 1].argsort()]
3. Replace diagonal with 0
python
Copy
Edit
arr = np.random.randint(10, 99, (5, 5))
np.fill_diagonal(arr, 0)
4. Find common elements in two arrays
python
Copy
Edit
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
common = np.intersect1d(a, b)
5. Count frequency of each unique element
python
Copy
Edit
arr = np.array([1, 2, 2, 3, 4, 4, 4])
unique, counts = np.unique(arr, return_counts=True)
freq_dict = dict(zip(unique, counts))
6. Find top 3 largest values in an array
python
Copy
Edit
arr = np.array([10, 30, 20, 40, 50])
top3 = np.sort(arr)[-3:]    # [30 40 50]
7. Find positions where elements are divisible by 3
python
Copy
Edit
arr = np.array([3, 4, 6, 7, 9])
indices = np.where(arr % 3 == 0)
8. Replace all NaN with column means
python
Copy
Edit
arr = np.array([[1, 2, np.nan], [4, np.nan, 6]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

In [41]:
arr = np.random.randint(1, 100, (4, 5))
arr


array([[15, 59, 26, 35, 67],
       [74, 16, 54, 33, 54],
       [60, 35, 43, 55, 50],
       [14, 79, 28, 48, 86]])

In [45]:
max_row_index = np.sum(arr, axis=1)
np.argmax(max_row_index)
# max_row_index#=

3

In [46]:
arr = np.array([
    [1, 4, 2],
    [3, 1, 5],
    [7, 0, 6]
])

sorted_arr = arr[arr[:, 1].argsort()]
print("Sorted by 2nd column:\n", sorted_arr)


Sorted by 2nd column:
 [[7 0 6]
 [3 1 5]
 [1 4 2]]


In [47]:
arr = np.random.randint(10, 99, (5, 5))
print("Before:\n", arr)

np.fill_diagonal(arr, 0)
print("After replacing diagonal:\n", arr)


Before:
 [[36 92 55 14 72]
 [40 17 88 69 93]
 [18 73 30 41 54]
 [35 54 20 17 21]
 [82 41 63 96 77]]
After replacing diagonal:
 [[ 0 92 55 14 72]
 [40  0 88 69 93]
 [18 73  0 41 54]
 [35 54 20  0 21]
 [82 41 63 96  0]]


In [48]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

common = np.intersect1d(a, b)
print("Common elements:", common)


Common elements: [3 4]
