In [4]:
import numpy as np

arr = np.arange(1,31).reshape(5,6)

In [10]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [22]:
arr[2:,4:]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [33]:
arr[:,3].reshape(5,1)

array([[ 4],
       [10],
       [16],
       [22],
       [28]])